/*
 * ============================================================================
 * Program Name : ipv4_extractor.cpp -- IPv4 Address Extractor
 *
 * Description  : Interactive driver for the IPv4 address extractor, plus the
 *                extraction routine
 *
 *                    bool extractIPv4(const std::string& str,
 *                                     unsigned long& outAddress,
 *                                     int& outPort);
 *
 *                which finds at most one valid IPv4 address, with an optional
 *                ":port" suffix, inside an arbitrary string. All parsing and
 *                validation is written by hand, one character at a time, and
 *                all digit accumulation is done manually: no string-to-number
 *                conversions (atoi/atol/atoll/strtol/strtoul/strtod/stoi/
 *                stol/stoul/sscanf), no address parsers (inet_aton/inet_pton/
 *                inet_addr), and no regular expressions.
 *
 *                extractIPv4() is not wired into main() yet, so the input
 *                loop still discards each line. That comes later.
 *
 * Inputs       : Lines of arbitrary text typed on standard input. The
 *                case-sensitive line "END" terminates the program.
 * Outputs      : The prompt "Enter a string (or 'END' to quit): " for each
 *                line read, and "Program terminated." on exit.
 *
 * Creation Date: September 27, 2026
 *
 * ---------------------------------------------------------------------------
 * AI GENERATION DISCLOSURE
 * ---------------------------------------------------------------------------
 *  These parts of the code were generated by AI using Cursor Claude Opus 5, High Thinking.
 *
 *   - This header comment block
 *   - The input loop in main(), however read failiure was added by me.
 *   - The extractIPv4() function and its helpers: isDigitChar(),
 *     isAddressChar(), parseOctet(), parsePort(), and tryCandidateAt()
 * ============================================================================
 */

#include <iostream>  // std::cin, std::cout
#include <string>    // std::string, std::getline
#include <cctype>    // std::isdigit


/*
* Defines the grammar for the inputs of the code.
 */

static const unsigned int MAX_OCTET_VALUE = 255;    // largest legal octet.
static const unsigned int MAX_OCTET_DIGITS = 3;     // "255" is 3 digits.
static const unsigned int MAX_PORT_VALUE = 65535;   // largest legal port.
static const unsigned int MAX_PORT_DIGITS = 5;      // "65535" is 5 digits.

// Used to check if a character is a digit.
static bool isDigitChar(char c)
{
    return std::isdigit(static_cast<unsigned char>(c)) != 0;
}

static bool isAddressChar(char c)
{
    return isDigitChar(c) || c == '.' || c == ':';
}

/*
 * Parses one octet starting at pos.
 */
static bool parseOctet(const std::string& str, std::string::size_type& pos,
                       unsigned int& value)
{
    const std::string::size_type start = pos;
    unsigned int accumulated = 0;  // value built one digit at a time.
    unsigned int digitCount = 0;   // digits used so far.

    while (pos < str.size() && isDigitChar(str[pos])) {
        // a fourth digit means this is not an octet at all.
        if (digitCount == MAX_OCTET_DIGITS) {
            return false;
        }
        // manual base 10 accumulation, since conversions are not allowed.
        accumulated = accumulated * 10u + static_cast<unsigned int>(str[pos] - '0');
        ++digitCount;
        ++pos;
    }

    if (digitCount == 0) {
        return false;  // empty octet, like "1..2.3".
    }
    if (digitCount > 1 && str[start] == '0') {
        return false;  // leading zero, like "01".
    }
    if (accumulated > MAX_OCTET_VALUE) {
        return false;  // out of range, like "256".
    }

    value = accumulated;
    return true;
}

/*
 * Reads the port starting at pos. same rules as parseOctet, but up to 5 digits and a limit of 65535.
 */
static bool parsePort(const std::string& str, std::string::size_type& pos,
                      unsigned int& value)
{
    const std::string::size_type start = pos;
    unsigned int accumulated = 0;
    unsigned int digitCount = 0;

    while (pos < str.size() && isDigitChar(str[pos])) {
        // A sixth digit cannot be a port, so stop it here instead of overflowing.
        if (digitCount == MAX_PORT_DIGITS) {
            return false;
        }
        accumulated = accumulated * 10u + static_cast<unsigned int>(str[pos] - '0');
        ++digitCount;
        ++pos;
    }

    if (digitCount == 0) {
        return false;  // colon with nothing after it
    }
    if (digitCount > 1 && str[start] == '0') {
        return false;  // leading zero
    }
    if (accumulated > MAX_PORT_VALUE) {
        return false;  // out of range
    }

    value = accumulated;
    return true;
}

/*
 * Tries to match a whole address, and its optional port.
 */
static bool tryCandidateAt(const std::string& str, std::string::size_type start,
                           unsigned long& address, int& port)
{
    std::string::size_type pos = start;
    unsigned long packed = 0;  // the four octets shifted into one value.

    // four octets split by exactly three periods.
    for (int octetIndex = 0; octetIndex < 4; ++octetIndex) {
        if (octetIndex > 0) {
            if (pos >= str.size() || str[pos] != '.') {
                return false;  // missing period, or ran off the end.
            }
            ++pos;  // step over the period.
        }

        unsigned int octet = 0;
        if (!parseOctet(str, pos, octet)) {
            return false;
        }
        packed = (packed << 8) | static_cast<unsigned long>(octet);
    }

    // a ":port" may follow the fourth octet, and nothing else may.
    int parsedPort = -1;
    if (pos < str.size() && str[pos] == ':') {
        ++pos;  // step over the colon.
        unsigned int portValue = 0;
        if (!parsePort(str, pos, portValue)) {
            return false;
        }
        parsedPort = static_cast<int>(portValue);
    }

    // a stray '.' or ':' stuck on the end kills the match, like "192.168.1.1."
    // or "1.2.3.4:80:90". a trailing digit cannot happen here because the
    // scanners above are greedy.
    if (pos < str.size() && isAddressChar(str[pos])) {
        return false;
    }

    address = packed;
    port = parsedPort;
    return true;
}

/*
 * Returns true if a valid address was found, false otherwise.
 * On success: outAddress holds the 32-bit value,
 * and outPort holds the port number, or -1 if no port was present.
 * On failure: outAddress is set to 0 and outPort is set to -1.
 */
bool extractIPv4(const std::string& str, unsigned long& outAddress, int& outPort)
{
    // The failure values, only replaces stuff when a match is found.
    outAddress = 0;
    outPort = -1;

    for (std::string::size_type i = 0; i < str.size(); ++i) {
        // Must start with a digit.
        if (!isDigitChar(str[i])) {
            continue;
        }
        // Skip if it's part of a bigger number.
        if (i > 0 && isAddressChar(str[i - 1])) {
            continue;
        }

        unsigned long address = 0;
        int port = -1;
        if (tryCandidateAt(str, i, address, port)) {
            outAddress = address;
            outPort = port;
            return true;
        }
        // If this fails, keep looking for the next candidate.
    }

    return false;
}

int main()
{
    const std::string quitCommand = "END";  // defines the quit command.
    std::string line;                       // holds current input line.

    while (true) {
        std::cout << "Enter a string (or 'END' to quit): ";

        // read failiure is treated like end command.
        if (!std::getline(std::cin, line)) {
            std::cout << std::endl;
            break;
        }
        if (line == quitCommand) {
            break;
        }

        //will add the functionality for the loop after.
    }

    std::cout << "Program terminated." << std::endl;
    return 0;
}
