/*
 * ============================================================================
 * Program Name : ipv4_extractor.cpp -- IPv4 Address Extractor (input loop)
 *
 * Description  : Interactive driver for the IPv4 address extractor. This file
 *                currently contains only the input loop: it repeatedly prompts
 *                the user for a line of text and terminates when the user
 *                enters END. The extraction routine
 *
 *                    bool extractIPv4(const std::string& str,
 *                                     unsigned long& outAddress,
 *                                     int& outPort);
 *
 *                is not implemented yet and will be added in a later revision,
 *                at which point each input line will be passed to it and the
 *                result reported. When written, that routine must do all
 *                digit accumulation by hand: no string-to-number conversions
 *                (atoi/atol/atoll/strtol/strtoul/strtod/stoi/stol/stoul/
 *                sscanf), no address parsers (inet_aton/inet_pton/inet_addr),
 *                and no regular expressions.
 *
 * Inputs       : Lines of arbitrary text typed on standard input. The
 *                case-sensitive line "END" terminates the program.
 * Outputs      : The prompt "Enter a string (or 'END' to quit): " for each
 *                line read, and "Program terminated." on exit.
 *
 * Creation Date: September 27, 2026
 *
 * ---------------------------------------------------------------------------
 * AI GENERATION DISCLOSURE
 * ---------------------------------------------------------------------------
 *  These parts of the code were generated by AI using Cursor Claude Opus 5, High Thinking.
 *
 *   - This header comment block
 *   - The input loop in main()
 *   - 
 * ============================================================================
 */

#include <iostream>  // std::cin, std::cout
#include <string>    // std::string, std::getline


int main()
{
    const std::string quitCommand = "END";  // defines the quit command.
    std::string line;                       // holds current input line.

    while (true) {
        std::cout << "Enter a string (or 'END' to quit): ";

        // read failiure is treated like end command.
        if (!std::getline(std::cin, line)) {
            std::cout << std::endl;
            break;
        }
        if (line == quitCommand) {
            break;
        }

        //will add the functionality for the loop after.
    }

    std::cout << "Program terminated." << std::endl;
    return 0;
}
